---
# Set up dev tools to be used on a server

- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: Setting up a server
    debug:
      msg: "Installing dev env on a server"

  - name: Install developer tools
    import_role:
      name: ../roles/install-dev-tools
  
  - name: Distribute authentication keys
    import_role:
      name: ../roles/key-distribution
  
  - name: Configure system and tools
    import_role:
      name: ../roles/spacekatt-config
