---
# Installs build tools

- name: Install Packages
  block:
  - name: Install build packages from apt
    apt:
      state: present
      pkg:
        - build-essential # contains - g++, gcc, make, libc6-dev, dpkg-dev
        - automake
        - cmake
        - libtool
        - autoconf
        - aptitude
