---
# Installs build tools

- name: Install Packages
  block:
  - name: Install build packages from apt
    become: true
    apt:
      name: '{{ packages }}'
      update_cache: yes
      state: present
    vars:
      packages:
      - build-essential
      - automake
      - cmake
      - libtool
      - autoconf
      - aptitude
