---
# Set up dev tools to be used on a server

- name: Install developer tools
  import_role: ../roles/install_dev_tools

#- name: Distribute authentication keys
  #import_role: ../roles/key_distribution

#- name: Configure system and tools
  #import_role: ../roles/spacekatt_config
